### ISSUE TITLE
现在还能正常使用吗？

### ISSUE THREAD

**Issue by drtwww** [zytomorrow/picgo-plugin-coding#17]
我自己测试不能用，呜呜。登陆步骤出错。

**Comment by zytomorrow** [comment]
麻烦贴一些日志，我确认下

**Comment by fengguowudi** [comment]
Error: No node found for selector: #login > div > div.auth-root-3ssdaLNMpv > main > div.form-container-1lsWy1AThz > form > div.form-content-32QJSI8qUW > div.info-login-3niBdtBCEI > label > div > span > input
    at Object.exports.assert (/Users/eyefulyou/Library/Application Support/picgo/node_modules/puppeteer/lib/cjs/puppeteer/common/assert.js:26:15)
    at DOMWorld.click (/Users/eyefulyou/Library/Application Support/picgo/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:276:21)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async getCookies (/Users/eyefulyou/Library/Application Support/picgo/node_modules/picgo-plugin-coding/src/index.js:36:3)
    at async Object.handle (/Users/eyefulyou/Library/Application Support/picgo/node_modules/picgo-plugin-coding/src/index.js:88:35)
    at async Lifecycle.doUpload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/core/Lifecycle.js:77:9)
    at async Lifecycle.start (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/core/Lifecycle.js:23:13)
    at async PicGo.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/src/core/PicGo.js:193:21)
    at async Object.upload (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:16:28227)
    at async Tt.upload (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:16:33348)

**Comment by fengguowudi** [comment]
报错这个

**Comment by fengguowudi** [comment]
然后lite版的浏览器位置是啥意思

**Comment by zytomorrow** [comment]
已修复，请安装最新版本，同时重新配置
