### ISSUE TITLE
浏览器位置填什么？

### ISSUE THREAD

**Issue by zwsn** [zytomorrow/picgo-plugin-coding#21]
填chrome的位置，上传报错。
位置：/Applications/Google\ Chrome.app
日志：
2021-10-11 16:51:30 [PicGo INFO] Before transform 
2021-10-11 16:51:30 [PicGo INFO] Transforming... Current transformer is [path] 
2021-10-11 16:51:30 [PicGo INFO] Before upload 
2021-10-11 16:51:30 [PicGo INFO] beforeUploadPlugins: renameFn running 
2021-10-11 16:51:30 [PicGo INFO] Uploading... Current uploader is [coding-lite] 
2021-10-11 16:51:30 [PicGo WARN] failed 
2021-10-11 16:51:30 [PicGo ERROR] 
------Error Stack Begin------
Error: Failed to launch the browser process! spawn image ENOENT

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/Users/limuby/Library/Application Support/picgo/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at ChildProcess.<anonymous> (/Users/limuby/Library/Application Support/picgo/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:185:85)
    at ChildProcess.emit (events.js:200:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
-------Error Stack End------- 
2021-10-11 16:51:30 [PicGo ERROR] 
------Error Stack Begin------
Error: Failed to launch the browser process! spawn image ENOENT

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/Users/limuby/Library/Application Support/picgo/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at ChildProcess.<anonymous> (/Users/limuby/Library/Application Support/picgo/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:185:85)
    at ChildProcess.emit (events.js:200:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
-------Error Stack End-------

**Comment by zytomorrow** [comment]
已修复，请安装最新版本，同时重新配置

**Comment by zwsn** [comment]
非常感谢,m1测试正常

**Comment by zytomorrow** [comment]
😁

**Comment by zwsn** [comment]
仓忙测试,提示上传成功,我以为就正常了.实际上提示上传成功,并没有上传,picgo的相册列表也没显示,也没有自动复制链接.去coding仓库看也没有提交记录和图片.

本来以为是文件名的问题,因为用的另一个插件会有文件名提示.但是尝试改名之后,还是一样.测试设备是12.2.1的m1,在外地intel设备没测.

**Comment by zytomorrow** [comment]
我本地测试成功了，方便的话给我截图一下你的配置信息，我确认下

**Comment by zwsn** [comment]
<img width="836" alt="image" src="https://user-images.githubusercontent.com/42889307/156957755-3fe49b51-98ba-4614-8148-3cff67117f83.png">
<img width="836" alt="image" src="https://user-images.githubusercontent.com/42889307/156957772-27f98fc6-1f28-4a54-a050-dc4840b58190.png">
<img width="686" alt="image" src="https://user-images.githubusercontent.com/42889307/156957864-e7d0b487-8a6c-4fbe-a784-6c97a25a0e10.png">

**Comment by zytomorrow** [comment]
团队名称和项目名称都需要填，coding是团队名，项目名，仓库三个层级🌝🌝你看下readme那个填法

**Comment by zwsn** [comment]
非常感谢作者的耐心回答,怪我没注意.重新配置后可以上传成功,但是不会自动复制链接,相册列表依然不显示上传过的图片.开始怀疑是不是picgo的问题了,尝试过重启,问题依旧.
<img width="836" alt="image" src="https://user-images.githubusercontent.com/42889307/156965013-ebfb6954-89a1-4c69-a79b-2aaa69af1e84.png">
<img width="686" alt="image" src="https://user-images.githubusercontent.com/42889307/156965117-965e6035-9d4e-422a-869c-78f67cb8d02b.png">

**Comment by zytomorrow** [comment]
![1646625409(1)](https://user-images.githubusercontent.com/16175551/156965334-3da35515-2249-4c51-865c-5f1750fee5c6.png)
我本地正常，请尝试再安装下下试试呢

**Comment by zwsn** [comment]
确实是picgo本身的问题,尝试删除 picgo.db，删除配置文件 data.json 然后重命名 config-bak.json -> data.json后,重启picgo就正常了

**Comment by zytomorrow** [comment]
ok，找到原因就行，后面我再复现下，看能否解决👌
