### ISSUE TITLE
上传错误 No node found for selector

### ISSUE THREAD

**Issue by Ainrie** [zytomorrow/picgo-plugin-coding#23]
按照教程设置后还是上传不了，可以帮我看看是什么原因么？日志如下：

2022-01-15 21:16:55 [PicGo ERROR] 
------Error Stack Begin------
Error: No node found for selector: #login > div > div.auth-root-3ssdaLNMpv > main > div.form-container-1lsWy1AThz > form > div.form-content-32QJSI8qUW > div.info-login-3niBdtBCEI > label > div > span > input
    at Object.exports.assert (C:\Users\Ai\AppData\Roaming\picgo\node_modules\puppeteer\lib\cjs\puppeteer\common\assert.js:26:15)
    at DOMWorld.click (C:\Users\Ai\AppData\Roaming\picgo\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:276:21)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async getCookies (C:\Users\Ai\AppData\Roaming\picgo\node_modules\picgo-plugin-coding\src\index.js:36:3)
    at async Object.handle (C:\Users\Ai\AppData\Roaming\picgo\node_modules\picgo-plugin-coding\src\index.js:88:35)
    at async Lifecycle.doUpload (C:\Users\Ai\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:80:9)
    at async Lifecycle.start (C:\Users\Ai\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:26:13)
    at async PicGo.upload (C:\Users\Ai\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:205:32)
    at async Object.upload (C:\Users\Ai\AppData\Local\Programs\PicGo\resources\app.asar\background.js:36:29196)
    at async Pt (C:\Users\Ai\AppData\Local\Programs\PicGo\resources\app.asar\background.js:36:31625)
-------Error Stack End------- 

![截图_20222115092112](https://user-images.githubusercontent.com/63640523/149623223-2a35fbe3-4913-4caa-9ed4-801864336ee0.png)
![截图_20222115092129](https://user-images.githubusercontent.com/63640523/149623233-1ee63189-6472-4803-bd63-0243d0193948.png)

**Comment by zytomorrow** [comment]
目前API变更了，暂时无法有好的方式进行授权，还在考虑中

**Comment by Ainrie** [comment]
期待修复

**Comment by zytomorrow** [comment]
好的，我确认下coding是否已经完成新API迁移，迁移后进行修复。（不然它又改了就白做了）🤣

**Comment by zytomorrow** [comment]
已修复，请安装最新版本，同时重新配置

**Comment by icat233** [comment]
感谢大佬！

**Comment by zytomorrow** [comment]
npm安装可能有延迟，请确保版本号≥2.0
