### ISSUE TITLE
上传错误[PicGo ERROR]: TypeError: Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by Vlary** [zytomorrow/picgo-plugin-coding#32]
日志如下：
[PicGo ERROR]: TypeError: Cannot read properties of undefined (reading '0')
    at getLastCommitSha (/home/vlary/.config/picgo/node_modules/picgo-plugin-coding/src/index.js:77:35)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.handle (/home/vlary/.config/picgo/node_modules/picgo-plugin-coding/src/index.js:170:27)
    at async xe.doUpload (/tmp/.mount_PicGo-dXGesT/resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:15103)
    at async xe.start (/tmp/.mount_PicGo-dXGesT/resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:13874)
    at async Nt.upload (/tmp/.mount_PicGo-dXGesT/resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:55699)
    at async Object.upload (/tmp/.mount_PicGo-dXGesT/resources/app.asar/background.js:2:575825)
    at async Oe (/tmp/.mount_PicGo-dXGesT/resources/app.asar/background.js:2:578543)

**Comment by zytomorrow** [comment]
暂时未复现，稍后处理

**Comment by ad-vancing** [comment]
我也出现了这个问题，进过多次实验，发现是参数写的不对。日志里可以打印一下就好了，hhh
